---

name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish (Dockerhub)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker build -t elementary/builds .

      - name: Publish
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          docker push elementary/builds:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    needs:
      - publish

    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v1

      - name: Deploy
        run: >
          echo "${{ secrets.KUBE_CERT }}" | base64 -d  > /tmp/elementary.crt

          kubectl \
            --server="${{ secrets.KUBE_SERVER }}" \
            --certificate-authority="/tmp/elementary.crt" \
            --token="${{ secrets.KUBE_TOKEN }}" \
            --namespace="builds" \
            rollout restart deployment builds
